### PR TITLE
jsonix and mappings as separate bundle

### PR DESCRIPTION
**Pull request by bartvde**
The idea would be to create a bundle separate from the edit bundle as it's likely these dependencies will change less and we can leverage caching. This could be a global export module

Low priority

### CODE REVIEW

**Comment by bartvde** [comment]
this broke loading of saved maps e.g. http://localhost:8001/examples/full-example.html#/maps/1193/data/

ReferenceError: owjs is not defined
    at parseResult (story-tools-edit.js:436)

**Comment by bartvde** [comment]
okay that's just a typo

**Comment by ischneider** [comment]
So the typo is part of the saved map?

**Comment by bartvde** [comment]
It's a typo in the code that prevents WFS DescribeFeatureType

should be addressed with #199 as well

**Comment by ischneider** [comment]
Gotcha. Realized the typo later :smile:

**Pull request merged**
