### PR TITLE
default vector style does not match default style of style editor

### PR DESCRIPTION
**Pull request by bartvde**
screen shot 2015-01-19 at 14 56 13

### CODE REVIEW

**Comment by bartvde** [comment]
WIP PR attached, likely needs a few more polishes, will update soon

**Comment by ischneider** [comment]
> @ischneider is there a specific reason we only have simple and unique currently for line styles?

Just a lack of implementation so far. There are three others - I'll create issues for them.

**Comment by ischneider** [comment]
@bartvde hold on on this - I have addressed some of this in my WIP over the weekend.

**Comment by ischneider** [comment]
minor conflict was easily handled

**Pull request merged**
