### PR TITLE
Add a viewer example

### LINKED ISSUE #202: make viewer example
and load from config using storymap

### PR DESCRIPTION
**Pull request by bartvde**
closes #202

### CODE REVIEW

**Comment by bartvde** [comment]
@ischneider this is also ready for review. I decided to keep everything in a single module to make it easier, but you can create non editable components for the viewer example so that the whole OGC cruft is not needed run-time there. I've also moved the module to core instead of edit since it's used for both composer and viewer example.

**Comment by bartvde** [comment]
Since common is not really common anymore, I should separate it out into viewer.js and composer.js

**Comment by bartvde** [comment]
screen shot 2015-05-13 at 19 19 32

**Comment by ischneider** [comment]
Nice work, @bartvde 
I'm going to rebase my storypins wip on this and see if I have any feedback otherwise will probably just say merge :smile:

**Comment by bartvde** [comment]
okay this specific PR did not break styling but the #211 probably did

**Comment by bartvde** [comment]
@ischneider styling and debug panels fixed, any objection to merging?

**Comment by bartvde** [comment]
also feel free to merge if I'm not around

**Comment by ischneider** [comment]
thanks @bartvde

**Pull request merged**
