### PR TITLE
saving annotations on new map does not work

### PR DESCRIPTION
**Pull request by bartvde**
because the storymap does not have an id as yet it seems

but also circular reference somewhere

screen shot 2015-06-01 at 13 26 47

### CODE REVIEW

**Comment by bartvde** [comment]
@ischneider it seems that new annotations are in ms, whereas old ones (from existing map stories) are in seconds. Do you have a good idea for distinguishing between them? Currently when loading a newly saved annotation the time is wrongly multiplied by 1000 upon load.

**Comment by bartvde** [comment]
there is also an issue with displaying of geometries, it seems that in filterVectorLayer the range is messed up.

**Comment by davisc** [comment]
@bartvde can you describe the issue you are seeing with displaying geometries?

**Comment by bartvde** [comment]
@davisc so I create a new map with composer, add the dams0 layer from mapstory, then digitise a polygon for a story pin. Save the map. Reload the browser and load the saved map. The story pin will not show up.

**Comment by bartvde** [comment]
@davisc I had to make a few fixes (see last commit in this PR) to even get to this stage though.

**Comment by davisc** [comment]
@bartvde ok yeah I'm reviewing now.

**Comment by bartvde** [comment]
my guess is that either the storyPinsLayer was not added to the map in this case or it's below the tile layer, hope to confirm this theory soon

**Comment by bartvde** [comment]
The base layer seems to replace the storyPins layer

**Comment by bartvde** [comment]
ah clear is called and it removes the storyPins layer, it probably should not do this

**Comment by bartvde** [comment]
okay found a fix

**Comment by bartvde** [comment]
okay so the only remaining issue on this PR is how to distinguish between the different time units (ms and s) for old and new annotations

**Comment by bartvde** [comment]
Okay last issue also addressed (ideally this should be done when the transform the old mapstories to the new config format), so should be ready for review now. I can load annotations from old maps as well as new ones now.

screen shot 2015-06-02 at 13 39 19
screen shot 2015-06-02 at 13 39 02

**Comment by bartvde** [comment]
So ready for review now.

**Comment by bartvde** [comment]
@davisc any objection to me merging this one?

**Comment by ischneider** [comment]
> @ischneider it seems that new annotations are in ms, whereas old ones (from existing map stories) are in seconds. Do you have a good idea for distinguishing between them? Currently when loading a newly saved annotation the time is wrongly multiplied by 1000 upon load.

sorry @bartvde , was offline for a bit. Best bet it seems is to apply the change on saving (/1000) and reverse (*1000) on loading.

**Comment by bartvde** [comment]
okay let me finish this one off based on Ian's last comment

**Pull request merged**
