### PR TITLE
start 'full' example, incomplete and breaking

### PR DESCRIPTION
**Pull request by ischneider**
- design similar to intended working final look
- cleanup and unify some logic from other examples into common
- add placemarks for boxes and pins

breaks:

- other examples

### CODE REVIEW

**Comment by ischneider** [comment]
@bartvde:

As noted, this is incomplete... Check it out and let me know what you think.

Let me know if this is causing conflicts with any pending work you have and we can sort it out.

**Comment by ischneider** [comment]
@bartvde sorry, should have been clearer - this wasn't intended for merging yet

**Comment by bartvde** [comment]
ah okay, no problem to leave it as is though, I got most things to work fine in the full example.

Is it your intention to resurrect the other older examples? Or will we stick with this single one?

**Comment by ischneider** [comment]
If you got stuff working then OK I guess.

I was going to keep the other examples working for the sake of having multiple approaches but I suppose it's OK to drop them, too.

**Pull request merged**
