### PR TITLE
see if we can limit the number of SLD REST updates

### PR DESCRIPTION
**Pull request by bartvde**
it seems they go out too often now, at least verify this is not the case

### CODE REVIEW

**Comment by bartvde** [comment]
also if selecting the color ramp last, a second WPS request will go off which is not needed

**Comment by ischneider** [comment]
@bartvde Thanks for looking into these.

I'm wondering if some of these checks should go elsewhere? I could see providing a service that answers these questions based on the state of the style or we could create a real 'style' object :smile:

Currently, the controller watches the `activeStyle` and if the form is valid, updates the style on the layer and invokes a callback. There are still reasons to watch for intermediate changes that result in an incomplete state (like eventually dealing w/ an undo/redo stack and saving).

In general, it seems like we should:
* unify business logic regarding style completeness in service or style object - easier to test and understand
* add more validity checking to forms when appropriate (like checking if an attribute is selected for classification)
* have controller compute completeness and emit this as part of a style change - like `callback(isComplete)`

**Comment by bartvde** [comment]
right I also got the feeling I wasn't always in the right place here ;-)

**Comment by bartvde** [comment]
I am going to close this one and will revisit this one later

**Comment by ischneider** [comment]
Can we label as `backlog` or such?

**Comment by bartvde** [comment]
I'll create a new ticket @ischneider so we don't forgot to revisit. But since I added a PR to this one already with hub, I don't think there is a way to unlink.

**Pull request closed without merging**
