### PR TITLE
Fix up load local map dialog. Make sure JSON actually works

### PR DESCRIPTION
**Pull request by bartvde**

### CODE REVIEW

**Comment by bartvde** [comment]
We also need: https://github.com/openlayers/ol3/pull/3224 to serialize MapQuest sources

**Comment by ischneider** [comment]
@bartvde thanks for catching those mistakes

**Comment by bartvde** [comment]
np, do my changes to the template make any sense?

**Comment by ischneider** [comment]
Yes, I tried using an angular-ui drop down but for whatever reason, it wasn't working... so quickly hacked in the select. Obviously it's a temporary thing :smile:

**Comment by bartvde** [comment]
Let me add save and load from vector and then I'll merge this

**Comment by bartvde** [comment]
changed my mind, I'll merge this now and will handle vector in a subsequent PR

**Pull request merged**
